# 3.1 Colour based segmentation
This part consists of using colour based information
to segment individual images from a pumpkin field.
The segmented images should end up having a black
background with smaller white objects on top.

## Exercise 3.1.1
Annotate some pumpkins in a test image and extract information about the average pumpkin colour
in the annotated pixels. Calculate both mean value
and standard variation. Use the following two colour
spaces: RGB and CieLAB. Finally try to visualise
the distribution of colour values.

In [1]:
import cv2
import matplotlib.pyplot as plt
import numpy as np

img_true = cv2.imread('Ground_true_EB-02-660_0594_0326.jpg')
img_bgr = cv2.imread('Images/EB-02-660_0594_0326.jpg')
cv2.imwrite(filename="output/1/1/BGR/img.png", img=img_bgr)
img_lab = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2LAB)

### BGR

In [2]:
import cv2
import numpy as np

img_true = cv2.imread('output/1/1/BGR/Ground_true_EB-02-660_0594_0326.jpg')

img = cv2.imread('Images/EB-02-660_0594_0326.jpg')
cv2.imwrite("output/1/1/BGR/img.png", img)

# lower bound and upper bound for red color
lower_bound = np.array([0, 0, 250])	 
upper_bound = np.array([0, 0, 255])

# Find the colors within the boundaries
pixels = np.reshape(img, (-1, 3))
mask = cv2.inRange(img_true, lower_bound, upper_bound)
cv2.imwrite("output/1/1/BGR/mask.png", mask)
mask_pixels = np.reshape(mask, (-1))

img_bgr_pumpkins = cv2.bitwise_and(img, img, mask=mask)
cv2.imwrite("output/1/1/BGR/RGB.png", img_bgr_pumpkins)

# Mean and standard deviation
mean, std = cv2.meanStdDev(img, mask=mask)
print(f"Mean color values of the annotated pixels:\n {mean}")
print(f"Standard deviation of color values of the annotated pixels:\n {std}")

# Covariance
cov = np.cov(pixels.transpose(), aweights=mask_pixels)
print(f"Covariance matrix of color values of the annotated pixels:\n {cov}")

# Test the output
img = cv2.imread('Images/EB-02-660_0594_0344.jpg')
mask = cv2.inRange(img, mean-std, mean+std)
img_test = cv2.bitwise_and(img, img, mask=mask)
cv2.imwrite("output/1/1/BGR/test.png", img_test)

# Show the histogram
colors = ['b', 'g', 'r']
for dim in range(img_test.ndim):
    data =  np.reshape(img_test[:, :, dim], (-1))
    plt.hist(data[data != 0], bins=255, color=colors[dim], alpha=0.5)
plt.savefig("output/1/1/BGR/histogram.png")
plt.close()


Mean color values of the annotated pixels:
 [[ 46.41416428]
 [150.11533625]
 [230.19802827]]
Standard deviation of color values of the annotated pixels:
 [[21.71128969]
 [16.11388805]
 [17.11028936]]
Covariance matrix of color values of the annotated pixels:
 [[471.40381144 205.71747089 131.0308569 ]
 [205.71747089 259.6704494  231.02876867]
 [131.0308569  231.02876867 292.77672851]]


### CieLAB

In [ ]:
import cv2
import numpy as np

img_true = cv2.imread('output/1/1/CieLAB/Ground_true_EB-02-660_0594_0326.jpg')

img = cv2.imread('Images/EB-02-660_0594_0326.jpg')
cv2.imwrite("output/1/1/CieLAB/img.png", img)

# lower bound and upper bound for red color
lower_bound = np.array([0, 0, 250])	 
upper_bound = np.array([0, 0, 255])

# Find the colors within the boundaries
pixels = np.reshape(img, (-1, 3))
mask = cv2.inRange(img_true, lower_bound, upper_bound)
cv2.imwrite("output/1/1/CieLAB/mask.png", mask)
mask_pixels = np.reshape(mask, (-1))

img_CieLAB_pumpkins = cv2.bitwise_and(img, img, mask=mask)
cv2.imwrite("output/1/1/CieLAB/CieLAB.png", img_CieLAB_pumpkins)

# Mean and standard deviation
mean, std = cv2.meanStdDev(img, mask=mask)
print(f"Mean color values of the annotated pixels:\n {mean}")
print(f"Standard deviation of color values of the annotated pixels:\n {std}")

# Covariance
cov = np.cov(pixels.transpose(), aweights=mask_pixels)
print(f"Covariance matrix of color values of the annotated pixels:\n {cov}")

# Test the output
img = cv2.imread('Images/EB-02-660_0594_0344.jpg')
mask = cv2.inRange(img, mean-std, mean+std)
img_test = cv2.bitwise_and(img, img, mask=mask)
cv2.imwrite("output/1/1/CieLAB/test.png", img_test)

# Show the histogram
colors = ['b', 'g', 'r']
for dim in range(img_test.ndim):
    data =  np.reshape(img_test[:, :, dim], (-1))
    plt.hist(data[data != 0], bins=255, color=colors[dim], alpha=0.5)
plt.savefig("output/1/1/CieLAB/histogram.png")
plt.close()


Mean color values of the annotated pixels:
 [[ 46.41416428]
 [150.11533625]
 [230.19802827]]
Standard deviation of color values of the annotated pixels:
 [[21.71128969]
 [16.11388805]
 [17.11028936]]
Covariance matrix of color values of the annotated pixels:
 [[471.40381144 205.71747089 131.0308569 ]
 [205.71747089 259.6704494  231.02876867]
 [131.0308569  231.02876867 292.77672851]]


## Exercise 3.1.2
Segment the orange pumpkins from the background
using color information. Experiment with the following segmentation methods
1. inRange with RGB values
2. inRange with CieLAB values
3. Distance in RGB space to a reference colour
4. (HLS)

## Exercise 3.1.3
Choose one segmentation method to use for the rest
of the mini-project.

# 3.2 Counting objects
This part is about counting objects in segmented
images and then to generate some visual output that
will help you to debug the programs.

## Exercise 3.2.1
Count the number of orange blobs in the segmented
image.

## Exercise 3.2.2
Filter the segmented image to remove noise.

## Exercise 3.2.3
Count the number of orange blobs in the filtered image.

## Exercise 3.2.4
Mark the located pumpkins in the input image. This
step is for debugging purposes and to convince others
that you have counted the pumpkins accurately.

# 3.3 Generate an orthomosaic
This part deals with orthorectifying multiple images
of the same field into a single carthometric product.
Choose proper settings for all below processes, taking into consideration the available computing resources

## Exercise 3.3.1
Load data into Metashape.

## Exercise 3.3.2
Perform bundle adjustment (align photos) and check
results

## Exercise 3.3.3
Perform dense reconstruction

## Exercise 3.3.4
Create digital elevation model

## Exercise 3.3.5
Create orthomosaic

## Exercise 3.3.6
Limit orthomosaic to pumpkin field

# 3.4 Count in orthomosaic
Use the python package rasterio to perform operations on the orthomosaic using a tile based approach.

## Exercise 3.4.1
Create code that only loads parts of the orthomosaic.

## Exercise 3.4.2
Design tile placement incl. overlaps.

## Exercise 3.4.3
Count pumpkins in each tile.

## Exercise 3.4.4
Deal with pumpkins in the overlap, so they are only
counted once.

## Exercise 3.4.5
Determine amount of pumpkins in the entire field

# 3.5 Endnotes
Reflect on the conducted work in this miniproject.

## Exercise 3.5.1
Determine GSD and size of the image field. What is
the average number of pumpkins per area?

## Exercise 3.5.2
Reflect on whether the developed system is ready to
help a farmer with the task of estimating the number
of pumpkins in a field.